import type { Project } from "@/types/project";

export const MOCK_PROJECTS: readonly Project[] = [
  // ─── Verified ───────────────────────────────────────────────────────
  {
    slug: "aave",
    name: "Aave",
    description: "Lend and borrow with the leading DeFi protocol",
    long_description:
      "Aave is a decentralized non-custodial liquidity protocol where users can participate as depositors or borrowers on Arc.",
    status: "verified",
    category: "Lending",
    website: "https://aave.com",
    x_handle: "@aave",
    logo_placeholder: "AA",
    accent_color: "#B6509E",
    tasks: [
      {
        id: "aave_supply",
        title: "Supply USDC on Aave",
        description: "Deposit USDC into an Aave lending pool on Arc.",
        xp_reward: 30,
        task_type: "onchain",
        cta_label: "Complete Task",
        cta_href: "https://aave.com",
      },
      {
        id: "aave_borrow",
        title: "Borrow an Asset",
        description: "Borrow any supported asset from Aave on Arc.",
        xp_reward: 25,
        task_type: "onchain",
        cta_label: "Complete Task",
        cta_href: "https://aave.com",
      },
      {
        id: "aave_follow",
        title: "Follow Aave on X",
        description: "Follow the official Aave account on X.",
        xp_reward: 5,
        task_type: "social",
        cta_label: "Go to X",
        cta_href: "https://x.com/aaborrowable",
      },
    ],
    total_xp: 60,
    participants: 340,
  },
  {
    slug: "maple",
    name: "Maple Finance",
    description: "Institutional lending built for the onchain economy",
    long_description:
      "Maple Finance provides institutional borrowers access to undercollateralized loans through lending pools managed by Pool Delegates.",
    status: "verified",
    category: "Lending",
    website: "https://maple.finance",
    x_handle: "@maplefinance",
    logo_placeholder: "MF",
    accent_color: "#1A8C6D",
    tasks: [
      {
        id: "maple_deposit",
        title: "Deposit to a Maple Pool",
        description: "Supply assets to a Maple lending pool on Arc.",
        xp_reward: 30,
        task_type: "onchain",
        cta_label: "Complete Task",
        cta_href: "https://maple.finance",
      },
      {
        id: "maple_quiz",
        title: "Complete Maple Quiz",
        description: "Test your knowledge of the Maple protocol.",
        xp_reward: 20,
        task_type: "educational",
        cta_label: "Take Quiz",
        cta_href: "/quiz",
      },
      {
        id: "maple_follow",
        title: "Follow Maple on X",
        description: "Follow the official Maple Finance account on X.",
        xp_reward: 5,
        task_type: "social",
        cta_label: "Go to X",
        cta_href: "https://x.com/maplefinance",
      },
    ],
    total_xp: 55,
    participants: 180,
  },
  {
    slug: "curve",
    name: "Curve Finance",
    description: "Stablecoin swaps with deep liquidity on Arc",
    long_description:
      "Curve is an exchange liquidity pool on Arc designed for extremely efficient stablecoin trading and low-risk income for liquidity providers.",
    status: "verified",
    category: "DEX",
    website: "https://curve.fi",
    x_handle: "@curvefinance",
    logo_placeholder: "CF",
    accent_color: "#E64980",
    tasks: [
      {
        id: "curve_swap",
        title: "Swap Stablecoins on Curve",
        description: "Complete a stablecoin swap on Curve on Arc.",
        xp_reward: 25,
        task_type: "onchain",
        cta_label: "Complete Task",
        cta_href: "https://curve.fi",
      },
      {
        id: "curve_liquidity",
        title: "Add Liquidity to Curve",
        description: "Provide liquidity to a Curve pool on Arc.",
        xp_reward: 30,
        task_type: "onchain",
        cta_label: "Complete Task",
        cta_href: "https://curve.fi",
      },
      {
        id: "curve_follow",
        title: "Follow Curve on X",
        description: "Follow the official Curve Finance account on X.",
        xp_reward: 5,
        task_type: "social",
        cta_label: "Go to X",
        cta_href: "https://x.com/curvefinance",
      },
    ],
    total_xp: 60,
    participants: 290,
  },

  // ─── Community ──────────────────────────────────────────────────────
  {
    slug: "alpha",
    name: "Community Project Alpha",
    description: "Early stage project building on Arc",
    long_description:
      "An early-stage community project building financial primitives on Arc. Not audited. Do your own research.",
    status: "community",
    category: "DeFi",
    website: "#",
    x_handle: "@alpha_placeholder",
    logo_placeholder: "CA",
    accent_color: "#f59e0b",
    tasks: [
      {
        id: "alpha_interact",
        title: "Interact with Protocol",
        description: "Complete any transaction with the Alpha protocol.",
        xp_reward: 20,
        task_type: "onchain",
        cta_label: "Complete Task",
        cta_href: "#",
      },
      {
        id: "alpha_follow",
        title: "Follow Alpha on X",
        description: "Follow the Alpha project account on X.",
        xp_reward: 5,
        task_type: "social",
        cta_label: "Go to X",
        cta_href: "https://x.com/alpha_placeholder",
      },
    ],
    total_xp: 25,
    participants: 45,
  },
  {
    slug: "beta",
    name: "Community Project Beta",
    description: "Experimental yield protocol on Arc",
    long_description:
      "A community-driven experimental yield protocol building on Arc. Not audited. Do your own research.",
    status: "community",
    category: "DeFi",
    website: "#",
    x_handle: "@beta_placeholder",
    logo_placeholder: "CB",
    accent_color: "#f59e0b",
    tasks: [
      {
        id: "beta_interact",
        title: "Interact with Protocol",
        description: "Complete any transaction with the Beta protocol.",
        xp_reward: 20,
        task_type: "onchain",
        cta_label: "Complete Task",
        cta_href: "#",
      },
      {
        id: "beta_follow",
        title: "Follow Beta on X",
        description: "Follow the Beta project account on X.",
        xp_reward: 5,
        task_type: "social",
        cta_label: "Go to X",
        cta_href: "https://x.com/beta_placeholder",
      },
    ],
    total_xp: 25,
    participants: 32,
  },
  {
    slug: "gamma",
    name: "Community Project Gamma",
    description: "Community DEX aggregator on Arc",
    long_description:
      "A community-built DEX aggregator for the Arc ecosystem. Not audited. Do your own research.",
    status: "community",
    category: "DEX",
    website: "#",
    x_handle: "@gamma_placeholder",
    logo_placeholder: "CG",
    accent_color: "#f59e0b",
    tasks: [
      {
        id: "gamma_interact",
        title: "Interact with Protocol",
        description: "Complete any transaction with the Gamma protocol.",
        xp_reward: 20,
        task_type: "onchain",
        cta_label: "Complete Task",
        cta_href: "#",
      },
      {
        id: "gamma_follow",
        title: "Follow Gamma on X",
        description: "Follow the Gamma project account on X.",
        xp_reward: 5,
        task_type: "social",
        cta_label: "Go to X",
        cta_href: "https://x.com/gamma_placeholder",
      },
    ],
    total_xp: 25,
    participants: 18,
  },
] as const;

export function getProjectBySlug(slug: string): Project | undefined {
  return MOCK_PROJECTS.find((p) => p.slug === slug);
}

export function getProjectsByStatus(
  status: "verified" | "community",
): readonly Project[] {
  return MOCK_PROJECTS.filter((p) => p.status === status);
}
